CREATE TABLE CLIENTE
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(80)
);

CREATE TABLE PRODUTO
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(80),
    PRECO_UNITARIO NUMERIC(20,2)
);

CREATE TABLE PEDIDO
(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_ID INT REFERENCES CLIENTE(ID),
    DATA_PEDIDO TIMESTAMP,
    TOTAL NUMERIC(20,2)
);

CREATE TABLE ITEM_PEDIDO
(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    PEDIDO_ID INT REFERENCES PEDIDO(ID),
    PRODUTO_ID INT REFERENCES PRODUTO(ID),
    PRECO_UNITARIO NUMERIC(20,2),
    QUANTIDADE INTEGER
);